[package]
description = "Rapidash executor"
edition = "2021"
homepage = "https://github.com/lipicoder/rapidash"
license = "Apache-2.0"
name = "executor"
repository = "https://github.com/lipicoder/rapidash"
version = "0.1.0"
