[package]
description = "Rapidash Error Handling"
edition = "2021"
homepage = "https://github.com/lipicoder/rapidash"
license = "Apache-2.0"
name = "error"
repository = "https://github.com/lipicoder/rapidash"
version = "0.1.0"

[dependencies]

[lib]
name = "error"
path = "src/lib.rs"
